language: python

python:
  - "2.7"
  - "3.4"

env:
  global:
    - SECRET_KEY: "B6s/oNnp8SRbpWiIQJn/jtf3b50fJJLK8uErQsmlaN8Xfg6Fi"
    - TOX_ENV=py27-dj18
    - TOX_ENV=py27-djlast
    - TOX_ENV=py34-dj18
    - TOX_ENV=py34-djlast

install:
  - pip install -r requirements/test.txt
  - python setup.py install

script:
  - tox -r -e $TOX_ENV
